### ISSUE TITLE
仿真模式是否无法进行双向远程认证的？

### ISSUE THREAD

**Issue by joaquinboss** [asterinas/trustflow#66]
![微信图片_20240611114301](https://github.com/secretflow/trustedflow/assets/74462597/4250a288-9a80-44b1-891d-16591e559566)

大佬们，请问一下，这里的意思是不是意味着：仿真模式无法进行capsule-manager-sim与capsule-manager-sdk的双向远程认证的？

**Comment by tpppppub** [comment]
远程认证是需要 TEE 硬件支持的，仿真模式只是“仿真”，没有TEE安全特性，因此仅限于体验使用。

**Comment by joaquinboss** [comment]
> 远程认证是需要 TEE 硬件支持的，仿真模式只是“仿真”，没有TEE安全特性，因此仅限于体验使用。

好吧，感谢大佬。
还想问下大佬，那如果已经拥有SGX机器，走SGX模式的TEE，开启mTLS
执行步骤二的时候需要写上root-ca-file、private-key-file、cert-chain-file这三个文件吗？
![微信图片_20240611155331](https://github.com/secretflow/trustedflow/assets/74462597/debeac4c-db13-46bb-a748-a80db61e86da)
![微信图片_20240611155337](https://github.com/secretflow/trustedflow/assets/74462597/cd91bf68-7603-4c38-81f0-18054ffdb59b)

**Comment by tpppppub** [comment]
需要

**Comment by joaquinboss** [comment]
> 需要

好的，感谢大佬
还想问下，走SGX模式的时候，客户端为什么要将自己的私钥发送给飞地里面的可信APP？
按照常理，私钥一般都是用于解密和生成数字签名，是不能给别人知道的，那此处又为何要如此？
麻烦大佬再帮忙看两眼，感激不尽！
![微信图片_20240611193349](https://github.com/secretflow/trustedflow/assets/74462597/bafd3ac6-7865-4004-ab92-bbeff24e78f4)

**Comment by kaixin-haha** [comment]
@joaquinboss 这个客户端的私钥就是可信app的。在mtls中，客户端和服务端都拥有tls私钥
