### ISSUE TITLE
大佬们，想请教一下双向远程认证

### ISSUE THREAD

**Issue by joaquinboss** [asterinas/trustflow#71]
[看了大佬们在其它issue上的相关回答](https://github.com/secretflow/trustedflow/issues/42)
请问
server-cert-key、server-cert、client-ca-cert这三个文件是server.key、server.crt、client.crt吗？
root-ca-file、private-key-file、cert-chain-file这三个文件是ca.crt、client.key、client.crt吗？
![微信图片_20240618113921](https://github.com/secretflow/trustedflow/assets/74462597/7bc57418-4d78-4567-b9dc-4da6ba401eec)
![微信图片_20240611155337](https://github.com/secretflow/trustedflow/assets/74462597/db9406bd-62e6-4eb7-845c-6cc586d06601)

**Comment by zimu-yuxi** [comment]
可以根据该issue，去生成证书。你要先确认你当前操作是在哪个容器里，服务端证书/私钥在capsule-manager中使用，客户端证书/私钥在sdk侧使用
