### ISSUE TITLE
请问最新的CapsuleManager是不是有问题？

### ISSUE THREAD

**Issue by zzx-QDU** [asterinas/trustflow#81]
您好，我在最新的secretflow/capsule-manager-sgx-ubuntu22.04:latest镜像中运行occlum run /bin/capsule_manager --tls_config.enable_tls false时报错：

failed to boot up LibOS: ENOENT (#2, No such file or directory): EntryNotFound
[ERROR] occlum-pal: occlum_ecall_new_process returns ENOENT (line 210, file src/pal_api.c)

之前的版本没有出现过这一问题，请问是新版本需要增加新的步骤还是镜像有问题？

**Comment by zhongtianq** [comment]
sry，是文档中没有对应更新binary的名字。
现在的capsule manager提供grpc以及http两种api，所以对应的binary也有两个，可以在image/bin/下看到。

改成occlum run /bin/capsule_manager_grpc --tls_config.enable_tls false 就可以了，我会去fix一下文档

**Comment by zzx-QDU** [comment]
感谢，可以运行了。
