### ISSUE TITLE
并行任务上限

### ISSUE THREAD

**Issue by zzx-QDU** [asterinas/trustflow#83]
您好，我们现在用起多个容器的方法实现多个任务并行执行，但是我们不知道任务并行的上限如何确定。您能解答一下吗？

**Comment by wangzul** [comment]
可以提供一下服务器资源配置。

**Comment by zzx-QDU** [comment]
能否给一个简单的估算方法？我们以后可能会根据客户的服务器进行调整。

**Comment by wangzul** [comment]
并行执行任务的上限取决于CPU资源、内存等，理论来说不崩就行，建议通过kuscia或者k8s啥的管理

**Comment by zzx-QDU** [comment]
好的，感谢。就是按照一般并行的场景去处理，是我们想多了，以为TEE会比较特殊。
