### ISSUE TITLE
由于从中国国内下载docker hub trustflow相关镜像有困难，能否将相关镜像上传到中国国内的镜像源并给出地址，谢谢。

### ISSUE THREAD

**Issue by baoyibao99-baohan** [asterinas/trustflow#84]
由于从中国国内下载docker hub 中的 trustflow 相关镜像有困难，能否将相关镜像上传到中国国内的镜像源并给出地址，谢谢。

**Comment by zimu-yuxi** [comment]
可以使用阿里源，镜像地址加上secretflow-registry.cn-hangzhou.cr.aliyuncs.com，比如secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/capsule-manager-sim-ubuntu22.04:latest

**Comment by baoyibao99-baohan** [comment]
OK，thanks
