### ISSUE TITLE
PSI运行报错

### ISSUE THREAD

**Issue by JiaIcecream** [asterinas/trustflow#85]
你好！
我在运行PSI任务时出现了程序错误；
当我第一次运行PSI任务时出现的任务报错信息如下：
![1726823997488](https://github.com/user-attachments/assets/d1567745-f8e7-4446-b44f-33f91bb60041)

当我第二次运行PSI任务时出现了任务报错信息如下：
![1726824081784](https://github.com/user-attachments/assets/0d912c74-30d4-4327-904b-5567f29cda99)

这之后我运行PSI任务都会出现第二次运行时的报错信息，请问是什么造成了这个问题，或者能否提供一个排查的方向，谢谢。

**Comment by lanyy9527** [comment]
您好，看报错日志是因为这个文件无法删除，请尝试下手动删除这个文件后进行重试；

**Comment by JiaIcecream** [comment]
> 您好，看报错日志是因为这个文件无法删除，请尝试下手动删除这个文件后进行重试；
你好，我查看了容器中的/home/teeapp/task 目录，发现该目录下没有任何文件，这个目录是在什么地方，怎么查看到呢，谢谢。
![1727142252531](https://github.com/user-attachments/assets/f2a72c67-240f-40c1-b300-e5d2ccdf9190)

**Comment by lanyy9527** [comment]
您好，经过测试并没有重现您的问题，不排除是因为环境残留导致的，您可以尝试清理环境重新安装部署下；
