### ISSUE TITLE
PSI组件 支持的数据类型

### ISSUE THREAD

**Issue by JiaIcecream** [asterinas/trustflow#86]
你好，
我现在在使用trustflow运行psi任务，我想知道PSI组件支持哪些数据类型？ 包括主键支持哪些数据类型、特征支持哪些数据类型？ 期待您的回复，感谢。

**Comment by zhongtianq** [comment]
@JiaIcecream 
你好，bool, int, float, str都是支持的。其中，主键是str，并且内容是可以被转成float，会转成float处理。

**Comment by JiaIcecream** [comment]
> @JiaIcecream 你好，bool, int, float, str都是支持的。其中，主键是str，并且内容是可以被转成float，会转成float处理。

好的，谢谢回复

**Comment by JiaIcecream** [comment]
> @JiaIcecream 你好，bool, int, float, str都是支持的。其中，主键是str，并且内容是可以被转成float，会转成float处理。

你好，现在有两个问题。
第一个问题：看您说组件支持str，如果主键是例如：”34032219735662603A“ 这样的数据，没办法转换成float，是否就不支持；
第二个问题：标签支持哪些数据类型？ int和bool吗，float和str是否支持；
期待您的回复。
