### ISSUE TITLE
TrustedFlow后续有适配hyperenclave的计划吗

### ISSUE THREAD

**Issue by oceanqdu** [asterinas/trustflow#88]
现在投入使用的很多服务器中本身不具备TEE的特性，希望通过hyperenclave来支持机密计算，现在TrustedFlow还不支持hyperenclave，请问后续有支持的计划吗？

**Comment by BrainWH** [comment]
你好，后续计划到11月份会支持hyperenclave

**Comment by oceanqdu** [comment]
> 你好，后续计划到11月份会支持hyperenclave

感觉您的回复，期待新版本的发布
