### ISSUE TITLE
抓包结果不是TLS

### ISSUE THREAD

**Issue by zzx-QDU** [asterinas/trustflow#90]
您好，之前trustflow的一位老师跟我们交流时告诉我们，不开启mtls选项抓包结果也会是加密的，但是我们用wireshark试了一下，结果全部是TCP，请问是否必须开启mTLS加密选项才能让抓包结果为TLS，

感谢您的帮助！

**Comment by yuki252111** [comment]
不开启mtls的选项，加密的类型是数字信封，所以抓包不是TLS

**Comment by zzx-QDU** [comment]
好的，感谢。我们从介绍中找到了说明。
