### ISSUE TITLE
csv度量问题

### ISSUE THREAD

**Issue by walkovernamtso** [asterinas/trustflow#92]
快速上手上描述的是不支持CSV度量，而在csv情况下，sdk代码中policy配置了boot_measurement
请问是不是可以用cms_config 配置--mr-boot，怎么操作

附1 快速上手：
https://www.secretflow.org.cn/zh-CN/docs/trustflow/0.4.0b0/quick_start/step2
CSV模式下，CLI工具会对CapsuleManager所在的CSV VM进行远程认证。

您可以参照仿真模式下的说明，差别点仅在第1步需要做以下修改：

--tee-plat填写tee平台类型，目前支持sim/sgx/tdx/csv，CSV模式下填写csv。
由CSV VM的度量值暂无简易工具可以获取，CSV模式下我们暂时不对CapsuleManager的度量值进行限制，您可以保留远程认证报告用于后验。
cms_config --config-file alice.yaml init --host {CapsuleManager的服务地址} --tee-plat csv

附2 代码：

            if self.tee_plat == TEE_PLAT_SGX:
                rule.bool_debug_disabled = "true"
                rule.str_tee_platform = UAL_TEE_PLAT_SGX
                rule.hex_ta_measurement = self.tee_constraints.mr_ta
                rule.hex_signer = self.tee_constraints.mr_signer
            elif self.tee_plat == TEE_PLAT_TDX:
                rule.bool_debug_disabled = "true"
                rule.str_tee_platform = UAL_TEE_PLAT_TDX
                rule.hex_platform_measurement = self.tee_constraints.mr_plat
                rule.hex_boot_measurement = self.tee_constraints.mr_boot
                rule.hex_ta_measurement = self.tee_constraints.mr_ta
            elif self.tee_plat == TEE_PLAT_CSV:
                rule.str_tee_platform = UAL_TEE_PLAT_CSV
                rule.hex_boot_measurement = self.tee_constraints.mr_boot
            else:
                raise ValueError(f"Invalid TEE platform: {self.tee_plat}")

            report_json = json_format.MessageToJson(
                response.attestation_report, including_default_value_fields=True
            )
            policy_json = json_format.MessageToJson(
                policy, including_default_value_fields=True
            )
            verify_status = verifier.attestation_report_verify(report_json, policy_json)

**Comment by wangzul** [comment]
是的
cms_config --config-file xxxx init --mr-boot xxxx
![image](https://github.com/user-attachments/assets/bd51d881-e8b0-443a-8547-693de494b0f9)
cms_config命令只是辅助您对配置文件进行设置。您也可以不使用cms_config，手动修改yaml文件进行配置

**Comment by walkovernamtso** [comment]
好的了解这个方法了，那我要配置这个度量值，从哪里能获取到呢

**Comment by wangzul** [comment]
![image](https://github.com/user-attachments/assets/4ae9bc51-e0e7-465c-a407-fbd3d5b965fe)
执行这一步时你可以尝试查看CapsuleManager的日志，看能否找到度量值。

**Comment by asdfsx** [comment]
@wangzul 
在capsulemanager的日志里没有看到度量值。
截图中所说的保留远程认证报告怎么实现呢？
