### ISSUE TITLE
trustflow-ci-sim的镜像无法拉取

### ISSUE THREAD

**Issue by killomsc** [asterinas/trustflow#93]
### Issue Type

Build/Install

### Source

source

### Capsule Manager Version

0.1

### Capsule Manager SDK Version

0.1

### Tee Apps Version

0.1

### OS Platform and Distribution

linux

### Python version

3.8

### What happend and What you expected to happen.

```shell
dm_component中的dockerfile，涉及trustflow-ci-sim的仿真镜像无法拉取。
或者这个trustflow-ci-sim的dockerfile在哪？
```

### Reproduction code to reproduce the issue.

```shell
FROM secretflow/trustflow-ci-sim:0.1.0 as builder
```

**Comment by lanyy9527** [comment]
参考：https://www.secretflow.org.cn/zh-CN/docs/trustflow/0.4.0b0/quick_start/step1

**Comment by killomsc** [comment]
我是改了一点dm_component的代码，想要重新制作secretflow/sf-tee-dm-sim这个镜像。

**Comment by zhongtianq** [comment]
这个镜像是绑定secretpad的白屏界面产品allinone使用的，也已经很久没有迭代更新。
由于之前这个镜像之前是在内部打包的，所以有些依赖是没有publish到外部。 我尝试了一下在外部打包，镜像可以使用secretflow/trustflow-ci-ubuntu20.04:0.1.0b。
但是缺失了secretflow-spec==0.1.0.dev20231101这个python包，这个包没有在外部发布。对应的proto的地址是https://github.com/secretflow/spec/blob/main/secretflow/spec。

所以目前来说可能无法直接打出来这个镜像，可能需要手动制作一下这个python的包。

**Comment by killomsc** [comment]
@zhongtianq 好的，感谢，我试试
